name: Build and deploy Node.js project to Azure Function App - wc26

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: 'wc26-bfasg2adf8dza9hx'
          package: '.'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
